* Fileds missing from the output data:
** GPS Coordinates
	- a5 = geo_hh_loc-Latitude
	- a6 = geo_hh_loc-Longitude
	- a7 = geo_hh_loc-Altitude

* Adapted/Changed field names
** ID fields
	- id_b = id in section B
	- id_b2 = id in section B2 (labour)
	- id_c = id child
	- id_d = id woman
	- id_e = id parcel
	- id_f = id plot
	- id_g1 = id crop (not the crop code)
	- id_g2_1 = parcel ID, id_g2_2 = plot id, id_g2_3 = crop id(in repeat)
	- id_g4_1 = Crop id in G4 (not the codes)
	- id_h - crop ID in H
	- id_i - crop ID in I
	- id_j1 - animal Id in J1
	- id_j2 - animal Id in J2
	- id_e2 - parcel id in section E2 (made up section to collect parcel coordinates)
	- id_e18 - id of the parcel for which the area is measured
* Extra fields in the output data:
** All columns begin with have 'section_x-'
** Repeat groups begin with 'repeat_'
** Consent fields
	- consent_note1
	- consent_approve
	- consent_name
	- consent_signature
	- consent_note2
** CSV fields - fields retrieved from the listing data
	- csv_head_name
	- csv_head_age
	- csv_head_gender
	- csv_spouse_name
	- csv_spouse_age
	- csv_hh_members
	- csv_land
	- csv_land_minutes
** Auxiliary fields - used to calculate other fileds within the script
	- aux_a9a_a10a - datetime field used to calculate date and time of the 1st visit: a9a, a10a
	- aux_a9b_a10b - datetime field used to calculate date and time of the 2nd visit: a9b, a10b
	- aux_b2 - field to track the hh head to be set only once
	- aux_male(B) - field to track list of male IDs and names
	- aux_female(B) - field to track list of female IDs and names
	- aux_male_id(B) - field to track list of male IDs
	- aux_female_id(B) - field to track list of female IDs
	- aux_all_male(C) - list of all male used in Child Anthropometry section C ( id - name format)
	- aux_all_female(C) - list of all female used in Child Anthropometry section C ( id - name format)
	- aux_all_male(C) - list of all male used in Child Anthropometry section C (space-separated list of IDs)
	- aux_all_female(C) - list of all female used in Child Anthropometry section C (space-separated list of IDs)
	- aux_height_male_min(C) - pulled fields
	- aux_height_male_max(C)
	- aux_height_female_min(C)
	- aux_height_female_max(C)
	- aux_weight_male_min(C)
	- aux_weight_male_max(C)
	- aux_weight_female_min(C)
	- aux_weight_female_max(C)
	- aux_age - Calculated age based on declared birth month and year (D)
	- aux_e_rel(E) - 1 if parcel is relevant, 2 otherwise
	- aux_x_e3a, aux_x_e3b - parcel area value and unit
	- aug_g1_6 - sum of percentages of crop areas within plot
	- aux_g1_4a - sum of areas (crops), should be equal to parcel area
	- aux_g1_3_list - list of crop codes ' '- separated
	- aux_g4_1 - list of all crops
	- g1_4b_ha - G1 - crop area in ha
	- aux_g1_4_2 - sum of area in ha per plot
	- aux_g1_4_1 - sum of area in ha per parcel - should equal parcel area (more or less - fallow/trees)
	- aux_g1_5_2 - sum of percentages per plot, should add to 100
	- aux_f4a_1	- any portion of the parcel was left fallow
	- aux_f14a_1 - any trees on the parcel
	- aux_g1_4_per - percentage difference between sum of crop areas and parcel area in ha
	- aux_h1_list - list of selected crops in G1
	- aux_h1 - h1/crop label
	- aux_i_list - list of crops in I
	- aux_j1_1_list - list of animals in J1
	- aux_j1_3 - to test if the respondent has idea of any of the listed animal types
	- aux_j2_1_list - list of animals in J2
	- e3_ha - parcel area in ha
	- aux_e18 (inside repeat_e2) - ${}
	- aux_e2_ha_coef - conversion coef to hectares
	- aux_e2_ha - parcel area(declared) in hectare
	- aux_min_e18 - minimum area of all parcels (to check if any parce has measured area = 0 only 2 points measured)
	- aux_e18_per - percentage difference between measured area and declared area
	- aux_g2_rel - crop has been selected within G1, true/falseaux_g4_1
	- aux_g4_1 - crop has/doesn't have
	- aux_g1_4_tot - estimated total area on the plot
	- aux_parcel - list of one parcel id, area, distance
	- aux_all_parcels - list of all parcel ids, areas and distance
** Point coordinates
	- points - group of points
	- point_id - point id
	- point_e18 - point coordinate of parcel
	- aux_g2_all_crops - G2 list of all crops, long format


** Current fields
	- curr_a9a_a10a - date and time when enumertor reaches the start of the first section
	- curr_a9b_a10b - date and time when enumertor reaches the start of the second section
** Check fields - calculate fields used to display warning/error messages
	- chk_a9a_a10a - 1 if the measured date curr_a9a_a10a and the date entered by enumerator aux_a9a_a10a are on the same day, 2 otherwise. 1 - correct
	- chk_a9b_a10b - 1 if the measured date curr_a9b_a10b and the date entered by enumerator aux_a9b_a10b are on the same day, 2 otherwise. 1 - correct
	- chk_a13: 1 - if a13 = head name(from listing), 2 - otherwise. 1 - correct
	- chk_b2 = the number of times the hh head has been set. 1 - correct
	- chk_d3 = 1 - there's conflict between declared age and calculated age based on year/month of birth, 2 - no colflict. 2 - correct
	- chk_d3_all - chk_d3 for all women
	- chk_height_male (C) = check if male child height is within limits. 1 - correct
	- chk_height_female (C) = check if female child height is within limits. 1 - correct
	- chk_weight_male (C) = check if male child weight is within limits. 1 - correct
	- chk_weight_female (C) = check if female child weight is within limits. 1 - correct
	- chk_weights_heights (C) = check if there's any child weight or height outside the limits. 1 - correct
	- chk_d7_d8 (D) = value of maximum weight or height of woman, notify if > 250
	- chk_g1_5 (G1) = check sum of percentage of area planted with crops within plots. 1 - correct, 2 - fishy. Takes f4a(Fallow) and f14a(Trees) into account ( 1 - if percentages add up to 100 and no fallowing and no trees or percentages < 95 and some fallowing and some trees, 2 - otherwise)
	- chk_g1_4 = 1 if sum of areas planted with crop equal(or less for parcels left fallowing or with trees) the parcel area, 2 otherwise
	- chk_g1_4_per - percentage difference between sum of crop areas and parcel area in ha
	- chk_e18 = 1 - correct, 2- incorrect (there's at least one parcel for which the measured area and declared area differ by more than 10%)
	- e18 = 0  only 2 points have been captured
	- chk_e18_1 - measured and declared areas difer by more than 10% for the parcel id_e2
	- chk_e18 - There is at least one parce for which the measured and declared areas differ by more than 10%
	- chk_g1_5_2 - sum of percentages of areas occupied by crops within plot (1 - ok, 2, - not ok)
	- chk_g1_4_5 - check areas and percentages (1 - ok, 2 - not ok)
** Error/Warning notes displayed for the supervisor at the end, can be removed
	- err_a9a_a10a - displayed if chk_a9a_a10a != 1
	- err_a9b_a10b - displayed if chk_a9b_a10b != 1
	- err_a13 - displayed if chk_a13 != 1
	- err_b2 - displayed if chk_b2 != 1
	- err_g1_5a - displayed if chk_g1_5a = 2
	- err_g1_6 - displayed if chk_g1_6 = 2
** Note fields to display additional information, they can be removed
	- nt_xx
** Text fields used to jump between sections 'jump_', they can be removed

*** TODOs
	- make sure there's only one head selected - done
	- gps collection E18 after livestock - done
	- not assume the area units are the same in G1 as in E, pull from csv - done
	- conditions in H and I - done
	- check j1_15a if jr:choice-name works without definint a list - doesnt' work, to replace with pull labels
	- important  - Area of the parcel. This could be done summing up the area in G1_4 across the same G1_1 and then compare it directly with E3.
	- % of each crop in each plot. This could be calculated as the ratio between G1_4 for each line G1_3 across the same G1_2 in each G1_1. This ratio should be equal to G1_5 for each G1_3 in each G1_2 in each G1_1.
	- somethin in B9

*** Questions after training
	- Do we add None in F16
	- F7c allows decimals
	- is G4_9 refering to problems of the corresponding(a/b/c) variety in G4_8 or problems in general?
	- allow decimal in H2d
	- F5a - if the plot is used for livestock, it shouldn't ask this question
	- F4b, F4c - validation 2014 >= F4b + F4c
	- what is G1_6 if the crop is used for livestock
	- is I9 only asked once? for which crop

*** Questions
	- is section B2 asked only for the members three months or more y
	- what's the minimum age persons can be parents (aux_female, aux_male) 14
	- only interested in the parents of the measured children?
	- what are valud values for E3a, E6a?
	- valid ranges for F14, F13a, F7a
	- can I force crop area units to parcel area units
	- is the crop list at G4 same as the list in G1
	- need to -11, -16 instead of -99 for G4_8
*** Questions SurveyCTO
	- hide fields without disabling - cant' do
	- lowercase - cant do

*** Other
	- replace ^(\d+)[ ] with $1\t - to repalce first space after number with tab
	- important to maintain similar g1_3_list and garbes_g_crops_long.csv plus count of repeat_g2 = total number of crops
	- crop_has_varieties from garbes_g_crops_short.csv should match with garbes_g_varieties.csv



